version: 2.1

jobs:
  job_pre-commit:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - run: pre-commit run --all-files

workflows:
  test_and_build:
    jobs:
      - job_pre-commit