version: 2.1

jobs:
  job_pre-commit:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Pipfile.lock"}}
      - run:
          name: install dependencies
          command: pipenv install
      - run:
          name: run pre-commit
          command: pipenv run pre-commit run --all-files
      - save_cache:
          paths:
            - ~/.cache
        key: dependencies-{{ checksum "Pipfile.lock"}}

  job_build_image:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build and push
          command: |
            docker build -t $DOCKER_LOGIN/circleci-demo:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/circleci-demo:latest


workflows:
  test_and_build:
    jobs:
      - job_pre-commit
      - job_build_image:
          requires:
            - job_pre-commit